<?php

namespace App\Entity;

use App\Repository\AddressRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: AddressRepository::class)]
#[ORM\Table(name: '`address`')]
#[ORM\HasLifecycleCallbacks] 
class Address
{
    ################################
    ################################
    ########## ATTRIBUTES ##########
    ################################
    ################################

    /* The address ID, auto-generated by the database.
     * 
     * @var int|null
     */
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(['default'])]
    private ?int $id = null;

    /* The type of address (e.g., billing, shipping).
     * 
     * @var string|null
     */
    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Le type d'adresse ne peut pas être vide.")]
    #[Assert\Length(max: 255, maxMessage: "Le type d'adresse ne peut pas dépasser {{ limit }} caractères.")]
    #[Groups(['default'])]
    private ?string $type = null;

    /* The first name associated with the address.
     * 
     * @var string|null
     */
    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Le prénom ne peut pas être vide.")]
    #[Assert\Length(max: 255, maxMessage: "Le prénom ne peut pas dépasser {{ limit }} caractères.")]
    #[Groups(['default'])]
    private ?string $first_name = null;

    /* The last name associated with the address.
     * 
     * @var string|null
     */
    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Le nom de famille ne peut pas être vide.")]
    #[Assert\Length(max: 255, maxMessage: "Le nom de famille ne peut pas dépasser {{ limit }} caractères.")]
    #[Groups(['default'])]
    private ?string $last_name = null;

    /* The first line of the street address.
     * 
     * @var string|null
     */
    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "La première ligne de l'adresse ne peut pas être vide.")]
    #[Assert\Length(max: 255, maxMessage: "La première ligne de l'adresse ne peut pas dépasser {{ limit }} caractères.")]
    #[Groups(['default'])]
    private ?string $street1 = null;

    /* The second line of the street address (optional).
     * 
     * @var string|null
     */
    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\Length(max: 255, maxMessage: "La deuxième ligne de l'adresse ne peut pas dépasser {{ limit }} caractères.")]
    #[Groups(['default'])]
    private ?string $street2 = null;

    /* The city of the address.
     * 
     * @var string|null
     */
    #[ORM\Column(length: 100)]
    #[Assert\NotBlank(message: "La ville ne peut pas être vide.")]
    #[Assert\Length(max: 100, maxMessage: "La ville ne peut pas dépasser {{ limit }} caractères.")]
    #[Groups(['default'])]
    private ?string $city = null;

    /* The state or region of the address (optional).
     * 
     * @var string|null
     */
    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\Length(max: 255, maxMessage: "La région ou l'état ne peut pas dépasser {{ limit }} caractères.")]
    #[Groups(['default'])]
    private ?string $state = null;

    /* The country code of the address (ISO 3166-1 alpha-2 format).
     * 
     * @var string|null
     */
    #[ORM\Column(length: 2)]
    #[Assert\NotBlank(message: "Le code pays ne peut pas être vide.")]
    #[Assert\Length(max: 2, maxMessage: "Le code pays ne peut pas dépasser {{ limit }} caractères.")]
    #[Assert\Regex(pattern: "/^[A-Z]{2}$/", message: "Le code pays doit être au format ISO 3166-1 alpha-2.(2 lettres)")]
    #[Groups(['default'])]
    private ?string $country = null;

    /* The postal code of the address.
     * 
     * @var string|null
     */
    #[ORM\Column(length: 20)]
    #[Assert\NotBlank(message: "Le code postal ne peut pas être vide.")]
    #[Assert\Length(max: 20, maxMessage: "Le code postal ne peut pas dépasser {{ limit }} caractères.")]
    #[Groups(['default'])]
    private ?string $zip_code = null;

    /* The phone number associated with the address (optional).
     * 
     * @var string|null
     */
    #[ORM\Column(length: 20, nullable: true)]
    #[Assert\Length(max: 20, maxMessage: "Le numéro de téléphone ne peut pas dépasser {{ limit }} caractères.")]
    #[Assert\Regex(pattern: "/^\+?[0-9\s\-]+$/", message: "Le numéro de téléphone est invalide.")]
    #[Groups(['default'])]
    private ?string $phone = null;

    /* Indicates whether this address is the default address.
     * 
     * @var bool|null
     */
    #[ORM\Column]
    #[Groups(['default'])]
    private ?bool $is_default = null;

    /* The creation date of the address, automatically set when the address is created.
     * 
     * @var \DateTimeImmutable|null
     */
    #[ORM\Column]
    #[Groups(['default'])]
    private ?\DateTimeImmutable $created_at = null;

    ################################
    ################################
    ########## RELATIONS ###########
    ################################
    ################################

    /* The user associated with this address.
     * 
     * @var User|null
     */
    #[ORM\ManyToOne(inversedBy: 'addresses')]
    #[Groups(['default'])]
    private ?User $user = null;

    ################################
    ################################
    ########## LIFECYCLE ###########
    ################################
    ################################

    /*
     * Automatically sets the created_at field to the current date and time when the address is created.
     * 
     * @ORM\PrePersist
     */
    #[ORM\PrePersist]
    public function setCreatedAtValue(): void
    {
        if ($this->created_at === null) {
            $this->created_at = new \DateTimeImmutable();
        }
    }

    ###############################
    ######### CONSTRUCTOR #########
    ###############################

    /**
     * Address constructor.
     * Initializes the created_at field to the current date and time.
     */
    public function __construct()
    {
        $this->created_at = new \DateTimeImmutable();
    }

    ################################
    ################################
    ###### GETTERS & SETTERS #######
    ################################
    ################################

    /**
     * Getters and Setters for the Address entity.
     * 
     * These methods allow you to get and set the values of the address's attributes.
     */

    /*
     * Get the address ID.
     * 
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /*
     * Get the user associated with the address.
     * 
     * @return User|null
     */
    public function getUser(): ?User
    {
        return $this->user;
    }

    /*
     * Set the user associated with the address.
     * 
     * @param User|null $user
     * @return static
     */
    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    /*
     * Get the type of the address.
     * 
     * @return string|null
     */
    public function getType(): ?string
    {
        return $this->type;
    }

    /*
     * Set the type of the address.
     * 
     * @param string $type
     * @return static
     */
    public function setType(string $type): static
    {
        $this->type = $type;

        return $this;
    }

    /*
     * Get the first name associated with the address.
     * 
     * @return string|null
     */
    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    /*
     * Set the first name associated with the address.
     * 
     * @param string $first_name
     * @return static
     */
    public function setFirstName(string $first_name): static
    {
        $this->first_name = $first_name;

        return $this;
    }

    /*
     * Get the last name associated with the address.
     * 
     * @return string|null
     */
    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    /*
     * Set the last name associated with the address.
     * 
     * @param string $last_name
     * @return static
     */
    public function setLastName(string $last_name): static
    {
        $this->last_name = $last_name;

        return $this;
    }

    /*
     * Get the first line of the street address.
     * 
     * @return string|null
     */
    public function getStreet1(): ?string
    {
        return $this->street1;
    }

    /*
     * Set the first line of the street address.
     * 
     * @param string $street1
     * @return static
     */
    public function setStreet1(string $street1): static
    {
        $this->street1 = $street1;

        return $this;
    }

    /*
     * Get the second line of the street address (optional).
     * 
     * @return string|null
     */
    public function getStreet2(): ?string
    {
        return $this->street2;
    }

    /*
     * Set the second line of the street address (optional).
     * 
     * @param string|null $street2
     * @return static
     */
    public function setStreet2(?string $street2): static
    {
        $this->street2 = $street2;

        return $this;
    }

    /*
     * Get the city of the address.
     * 
     * @return string|null
     */
    public function getCity(): ?string
    {
        return $this->city;
    }

    /*
     * Set the city of the address.
     * 
     * @param string $city
     * @return static
     */
    public function setCity(string $city): static
    {
        $this->city = $city;

        return $this;
    }

    /*
     * Get the state or region of the address (optional).
     * 
     * @return string|null
     */
    public function getState(): ?string
    {
        return $this->state;
    }

    /*
     * Set the state or region of the address (optional).
     * 
     * @param string|null $state
     * @return static
     */
    public function setState(?string $state): static
    {
        $this->state = $state;

        return $this;
    }

    /*
     * Get the country code of the address.
     * 
     * @return string|null
     */
    public function getCountry(): ?string
    {
        return $this->country;
    }

    /*
     * Set the country code of the address.
     * 
     * @param string $country
     * @return static
     */
    public function setCountry(string $country): static
    {
        $this->country = $country;

        return $this;
    }

    /*
     * Get the postal code of the address.
     * 
     * @return string|null
     */
    public function getZipCode(): ?string
    {
        return $this->zip_code;
    }

    /*
     * Set the postal code of the address.
     * 
     * @param string $zip_code
     * @return static
     */
    public function setZipCode(string $zip_code): static
    {
        $this->zip_code = $zip_code;

        return $this;
    }

    /*
     * Get the phone number associated with the address (optional).
     * 
     * @return string|null
     */
    public function getPhone(): ?string
    {
        return $this->phone;
    }

    /*
     * Set the phone number associated with the address (optional).
     * 
     * @param string|null $phone
     * @return static
     */
    public function setPhone(?string $phone): static
    {
        $this->phone = $phone;

        return $this;
    }

    /*
     * Check if the address is the default address.
     * 
     * @return bool|null
     */
    public function isDefault(): ?bool
    {
        return $this->is_default;
    }

    /*
     * Set whether the address is the default address.
     * 
     * @param bool $is_default
     * @return static
     */
    public function setIsDefault(bool $is_default): static
    {
        $this->is_default = $is_default;

        return $this;
    }

    /**
     * Get the creation date of the address.
     * 
     * @return \DateTimeImmutable|null
     */
    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }
}
