<?php

namespace App\Entity;

use App\Repository\OrderItemRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: OrderItemRepository::class)]
#[ORM\Table(name: '`order_item`')]
class OrderItem
{
    ################################
    ################################
    ########## ATTRIBUTES ##########
    ################################
    ################################

    /* The order item ID, auto-generated by the database.
     * 
     * @var int|null
     */
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(['default'])]
    private ?int $id = null;

    /* The quantity of the product in this order item.
     * Must be a positive integer.
     * 
     * @var int
     */
    #[ORM\Column(type: Types::INTEGER, options: ['unsigned' => true])]
    #[Assert\NotNull]
    #[Assert\Positive]
    #[Groups(['default'])]
    private int $quantity = 1;

    /* The unit price of the product in this order item.
     * Must be a positive decimal value.
     * 
     * @var string|null
     */
    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2)]
    #[Assert\NotNull]
    #[Assert\Positive]
    #[Groups(['default'])]
    private ?string $unit_price = null;

    ################################
    ################################
    ########## RELATIONS ###########
    ################################
    ################################

    /* The order associated with this order item.
     * 
     * @var Order|null
     */
    #[ORM\ManyToOne(inversedBy: 'orderItems')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Order $order = null;

    /* The product associated with this order item.
     * 
     * @var Product|null
     */
    #[ORM\ManyToOne(inversedBy: 'orderItems')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Product $product = null;

    ################################
    ################################
    ###### GETTERS & SETTERS #######
    ################################
    ################################


    /*
     * Get the order item ID.
     * 
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /*
     * Get the order associated with this order item.
     * 
     * @return Order|null
     */
    public function getOrder(): ?Order
    {
        return $this->order;
    }

    /*
     * Set the order associated with this order item.
     * 
     * @param Order|null $order
     * @return static
     */
    public function setOrder(?Order $order): static
    {
        $this->order = $order;

        return $this;
    }

    /*
     * Get the product associated with this order item.
     * 
     * @return Product|null
     */
    public function getProduct(): ?Product
    {
        return $this->product;
    }

    /*
     * Set the product associated with this order item.
     * 
     * @param Product|null $product
     * @return static
     */
    public function setProduct(?Product $product): static
    {
        $this->product = $product;

        return $this;
    }

    /*
     * Get the quantity of the product in this order item.
     * 
     * @return int|null
     */
    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    /*
     * Set the quantity of the product in this order item.
     * 
     * @param int $quantity
     * @return static
     */
    public function setQuantity(int $quantity): static
    {
        $this->quantity = $quantity;

        return $this;
    }

    /*
     * Get the unit price of the product in this order item.
     * 
     * @return float|null
     */
    public function getUnitPrice(): ?float
    {
        return $this->unit_price;
    }

    /*
     * Set the unit price of the product in this order item.
     * 
     * @param float $unit_price
     * @return static
     */
    public function setUnitPrice(float $unit_price): static
    {
        $this->unit_price = $unit_price;

        return $this;
    }
}
