<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: OrderRepository::class)]
#[ORM\Table(name: '`order`')]
#[ORM\HasLifecycleCallbacks]
class Order
{
    ################################
    ################################
    ########## ATTRIBUTES ##########
    ################################
    ################################

    /* The order ID, auto-generated by the database.
     * 
     * @var int|null
     */
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    /* The user associated with the order.
     * 
     * @var User|null
     */
    #[ORM\ManyToOne(inversedBy: 'orders')]
    private ?User $user = null;

    /* The status of the order (e.g., pending, completed, cancelled).
     * 
     * @var string|null
     */
    #[ORM\Column(length: 50)]
    #[Assert\NotBlank]
    #[Assert\Choice(choices: ['pending', 'completed', 'cancelled'])]
    private ?string $status = null;

    /* The total amount of the order.
     * 
     * @var float|null
     */
    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2)]
    #[Assert\NotNull]
    #[Assert\PositiveOrZero]
    private ?float $total_amount = null;

    /* The shipping amount for the order.
     * 
     * @var float|null
     */
    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2)]
    #[Assert\NotNull]
    #[Assert\PositiveOrZero]
    private ?float $shipping_amount = null;

    /* The payment method used for the order.
     * 
     * @var string|null
     */
    #[ORM\Column(length: 50)]
    #[Assert\NotBlank]
    private ?string $payment_method = null;

    /* The payment status of the order (e.g., paid, unpaid).
     * 
     * @var string|null
     */
    #[ORM\Column(length: 50)]
    #[Assert\NotBlank]
    private ?string $payment_status = null;

    /* The tracking number for the order shipment (optional).
     * 
     * @var string|null
     */
    #[ORM\Column(length: 100, nullable: true)]
    #[Assert\Length(max: 100)]
    private ?string $tracking_number = null;

    /* Additional notes for the order (optional).
     * 
     * @var string|null
     */
    #[ORM\Column(type: Types::TEXT)]
    #[Assert\Length(max: 1000)]
    private ?string $notes = null;

    /* The shipping address associated with the order.
     * 
     * @var Address|null
     */
    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Address $shipping_address = null;

    /* The billing address associated with the order.
     * 
     * @var Address|null
     */
    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Address $billing_address = null;

    /* The creation date of the order.
     * 
     * @var \DateTimeImmutable|null
     */
    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    /* The last update date of the order.
     * 
     * @var \DateTimeImmutable|null
     */
    #[ORM\Column]
    private ?\DateTimeImmutable $updated_at = null;

    /* The collection of order items associated with the order.
     * 
     * @var Collection<int, OrderItem>
     */
    #[ORM\OneToMany(targetEntity: OrderItem::class, mappedBy: 'order', orphanRemoval: true)]
    private Collection $orderItems;

    ###############################
    ######### CONSTRUCTOR #########
    ###############################

    /**
     * Order constructor.
     * Initializes the orderItems collection and sets created_at to the current date.
     */
    public function __construct()
    {
        $this->orderItems = new ArrayCollection();
        $this->created_at = new \DateTimeImmutable();
    }

    ################################
    ################################
    ########## LIFECYCLE ###########
    ################################
    ################################

    /*
     * Automatically sets the created_at field to the current date and time when the order is created.
     * 
     * @ORM\PrePersist
     */
    #[ORM\PrePersist]
    public function setCreatedAtValue(): void
    {
        if ($this->created_at === null) {
            $this->created_at = new \DateTimeImmutable();
        }
    }

    /*
     * Automatically sets the updated_at field to the current date and time when the order is updated.
     * 
     * @ORM\PreUpdate
     */
    #[ORM\PreUpdate]
    public function setUpdatedAtValue(): void
    {
        $this->updated_at = new \DateTimeImmutable();
    }

    ################################
    ################################
    ###### GETTERS & SETTERS #######
    ################################
    ################################

    /**
     * Getters and Setters for the Order entity.
     * 
     * These methods allow you to get and set the values of the order's attributes.
     */

    /**
     * Get the order ID.
     * 
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * Get the user associated with the order.
     * 
     * @return User|null
     */
    public function getUserId(): ?User
    {
        return $this->user;
    }

    /**
     * Set the user associated with the order.
     * 
     * @param User|null $user
     * @return static
     */
    public function setUserId(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    /**
     * Get the status of the order.
     * 
     * @return string|null
     */
    public function getStatus(): ?string
    {
        return $this->status;
    }

    /**
     * Set the status of the order.
     * 
     * @param string $status
     * @return static
     */
    public function setStatus(string $status): static
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Get the total amount of the order.
     * 
     * @return float|null
     */
    public function getTotalAmount(): ?float
    {
        return $this->total_amount;
    }

    /**
     * Set the total amount of the order.
     * 
     * @param float $total_amount
     * @return static
     */
    public function setTotalAmount(float $total_amount): static
    {
        $this->total_amount = $total_amount;

        return $this;
    }

    /**
     * Get the shipping amount for the order.
     * 
     * @return float|null
     */
    public function getShippingAmount(): ?float
    {
        return $this->shipping_amount;
    }

    /**
     * Set the shipping amount for the order.
     * 
     * @param float $shipping_amount
     * @return static
     */
    public function setShippingAmount(float $shipping_amount): static
    {
        $this->shipping_amount = $shipping_amount;

        return $this;
    }

    /**
     * Get the payment method used for the order.
     * 
     * @return string|null
     */
    public function getPaymentMethod(): ?string
    {
        return $this->payment_method;
    }

    /**
     * Set the payment method used for the order.
     * 
     * @param string $payment_method
     * @return static
     */
    public function setPaymentMethod(string $payment_method): static
    {
        $this->payment_method = $payment_method;

        return $this;
    }

    /**
     * Get the payment status of the order.
     * 
     * @return string|null
     */
    public function getPaymentStatus(): ?string
    {
        return $this->payment_status;
    }

    /**
     * Set the payment status of the order.
     * 
     * @param string $payment_status
     * @return static
     */
    public function setPaymentStatus(string $payment_status): static
    {
        $this->payment_status = $payment_status;

        return $this;
    }

    /**
     * Get the tracking number for the order shipment (optional).
     * 
     * @return string|null
     */
    public function getTrackingNumber(): ?string
    {
        return $this->tracking_number;
    }

    /**
     * Set the tracking number for the order shipment (optional).
     * 
     * @param string|null $tracking_number
     * @return static
     */
    public function setTrackingNumber(?string $tracking_number): static
    {
        $this->tracking_number = $tracking_number;

        return $this;
    }

    /**
     * Get additional notes for the order (optional).
     * 
     * @return string|null
     */
    public function getNotes(): ?string
    {
        return $this->notes;
    }

    /**
     * Set additional notes for the order (optional).
     * 
     * @param string|null $notes
     * @return static
     */
    public function setNotes(?string $notes): static
    {
        $this->notes = $notes;

        return $this;
    }

    /**
     * Get the shipping address associated with the order.
     * 
     * @return Address|null
     */
    public function getShippingAddressId(): ?int
    {
        return $this->shipping_address;
    }

    /**
     * Set the shipping address associated with the order.
     * 
     * @param Address|null $shipping_address
     * @return static
     */
    public function setShippingAddressId(?Address $shipping_address): static
    {
        $this->shipping_address = $shipping_address;

        return $this;
    }

    /**
     * Get the billing address associated with the order.
     * 
     * @return Address|null
     */
    public function getBillingAddressId(): ?Address
    {
        return $this->billing_address;
    }

    /**
     * Set the billing address associated with the order.
     * 
     * @param Address|null $billing_address
     * @return static
     */
    public function setBillingAddressId(?Address $billing_address): static
    {
        $this->billing_address = $billing_address;

        return $this;
    }

    /**
     * Get the creation date of the order.
     * 
     * @return \DateTimeImmutable|null
     */
    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    /**
     * Set the creation date of the order.
     * 
     * @param \DateTimeImmutable $created_at
     * @return static
     */
    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * Get the last update date of the order.
     * 
     * @return \DateTimeImmutable|null
     */
    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    /**
     * Set the last update date of the order.
     * 
     * @param \DateTimeImmutable $updated_at
     * @return static
     */
    public function setUpdatedAt(\DateTimeImmutable $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * Get the collection of order items associated with the order.
     * 
     * @return Collection<int, OrderItem>
     */
    public function getOrderItems(): Collection
    {
        return $this->orderItems;
    }

    /**
     * Add an order item to the collection of order items.
     * 
     * @param OrderItem $orderItem
     * @return static
     */
    public function addOrderItem(OrderItem $orderItem): static
    {
        if (!$this->orderItems->contains($orderItem)) {
            $this->orderItems->add($orderItem);
            $orderItem->setOrderId($this);
        }

        return $this;
    }

    /**
     * Remove an order item from the collection of order items.
     * 
     * @param OrderItem $orderItem
     * @return static
     */
    public function removeOrderItem(OrderItem $orderItem): static
    {
        if ($this->orderItems->removeElement($orderItem)) {
            if ($orderItem->getOrderId() === $this) {
                $orderItem->setOrderId(null);
            }
        }

        return $this;
    }
}
