<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product
{
    ################################
    ################################
    ########## ATTRIBUTES ##########
    ################################
    ################################


    /* The product ID, auto-generated by the database.
     * 
     * @var int|null
     */
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    /* The product name, a string with a maximum length of 255 characters.
     * Must not be blank and must have a length between 3 and 255 characters.
     * 
     * @var string|null
     */
    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    #[Assert\Length(min: 3, max: 255)]
    private ?string $name = null;

    /* The product description, a text field that can be null.
     * If provided, it must not be blank and can have any length.
     * 
     * @var string|null
     */
    #[ORM\Column(type: Types::TEXT, nullable: true)]
    #[Assert\Length(min: 1, max: 1000, allowEmptyString: false)]
    private ?string $description = null;

    /* The product price, a decimal value with a precision of 10 and scale of 2.
     * Must be a positive value and cannot be null.
     * 
     * @var float|null
     */
    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2)]
    #[Assert\NotNull]
    #[Assert\Positive]
    private ?float $price = null;

    /* The product type, a string with a maximum length of 50 characters.
     * Must not be blank.
     * 
     * @var string|null
     */
    #[ORM\Column(length: 50)]
    #[Assert\NotBlank]
    private ?string $type = null;

    /* The product stock, an unsigned integer that must be greater than or equal to 0.
     * Represents the available quantity of the product.
     * 
     * @var int|null
     */
    #[ORM\Column(type: Types::INTEGER, options: ['unsigned' => true])]
    #[Assert\NotNull]
    #[Assert\GreaterThanOrEqual(0)]
    private ?int $stock = null;

    /* The product status, a string with a maximum length of 20 characters.
     * Must be either 'active' or 'inactive'.
     * 
     * @var string
     */
    #[ORM\Column(length: 20)]
    #[Assert\Choice(choices: ['active', 'inactive'])]
    private string $status = 'inactive';

    /* The product slug, a URL-friendly string with a maximum length of 255 characters.
     * Must not be blank and must be unique for SEO and readability purposes.
     * 
     * @var string|null
     */
    #[ORM\Column(length: 255, unique: true)]
    #[Assert\NotBlank]
    private ?string $slug = null; // url friendly name for best readability, SEO etc

    /* The product creation date, automatically set to the current date and time when the product is created.
     * 
     * @var \DateTimeImmutable|null
     */
    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    /* The product last update date, automatically set to the current date and time when the product is updated.
     * 
     * @var \DateTimeImmutable|null
     */
    #[ORM\Column]
    private ?\DateTimeImmutable $updated_at = null;


    ################################
    ################################
    ########## RELATIONS ###########
    ################################
    ################################

    /* The collection of order items associated with the product.
     * Represents the relationship between the product and the order items in which it is included.
     * Each order item corresponds to a specific instance of the product in an order.
     * 
     * @var Collection<int, OrderItem>
     */
    #[ORM\OneToMany(targetEntity: OrderItem::class, mappedBy: 'product', orphanRemoval: true)]
    private Collection $orderItems;


    ################################
    ################################
    ########## LIFECYCLE ###########
    ################################
    ################################

    /*
     * Automatically sets the created_at field to the current date and time when the product is created.
     * 
     * @ORM\PrePersist
     */
    #[ORM\PrePersist]
    public function setCreatedAtValue(): void
    {
        if ($this->created_at === null) {
            $this->created_at = new \DateTimeImmutable();
        }
    }

    /*
     * Automatically sets the updated_at field to the current date and time when the product is updated.
     * 
     * @ORM\PreUpdate
     */
    #[ORM\PreUpdate]
    public function setUpdatedAtValue(): void
    {
        
        $this->updated_at = new \DateTimeImmutable();
        
    }

    ###############################
    ######### CONSTRUCTOR #########
    ###############################

    /**
     * Product constructor.
     * Initializes the orderItems collection and sets created_at and updated_at to current date.
     */
    public function __construct()
    {
        $this->orderItems = new ArrayCollection();
        $this->created_at = new \DateTimeImmutable();
        $this->updated_at = new \DateTimeImmutable();
    }


    ################################
    ################################
    ###### GETTERS & SETTERS #######
    ################################
    ################################

    /**
     * Getters and Setters for the Product entity.
     * 
     * These methods allow you to get and set the values of the product's attributes.
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /*
     * Get the product name.
     * 
     * @return string|null
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /*
     * Set the product name.
     * 
     * @param string $name
     * @return static
     */
    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }
    
    /*
     * Get the product description.
     * 
     * @return string|null
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /*
     * Set the product description.
     * 
     * @param string|null $description
     * @return static
     */
    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    /*
     * Get the product price.
     * 
     * @return string|null
     */
    public function getPrice(): ?string
    {
        return $this->price;
    }

    /*
     * Set the product price.
     * 
     * @param float $price
     * @return static
     */
    public function setPrice(float $price): static
    {
        $this->price = $price;

        return $this;
    }

    /*
     * Get the product type.
     * 
     * @return string|null
     */
    public function getType(): ?string
    {
        return $this->type;
    }

    /*
     * Set the product type.
     * 
     * @param string $type
     * @return static
     */
    public function setType(string $type): static
    {
        $this->type = $type;

        return $this;
    }

    /*
     * Get the product stock.
     * 
     * @return int|null
     */
    public function getStock(): ?int
    {
        return $this->stock;
    }

    /*
     * Set the product stock.
     * 
     * @param int $stock
     * @return static
     */
    public function setStock(int $stock): static
    {
        $this->stock = $stock;

        return $this;
    }

    /*
     * Get the product status.
     * 
     * @return string|null
     */
    public function getStatus(): ?string
    {
        return $this->status;
    }

    /*
     * Set the product status.
     * 
     * @param string $status
     * @return static
     */
    public function setStatus(string $status): static
    {
        $this->status = $status;

        return $this;
    }

    /*
     * Get the product slug.
     * 
     * @return string|null
     */
    public function getSlug(): ?string
    {
        return $this->slug;
    }

    /*
     * Set the product slug.
     * 
     * @param string $slug
     * @return static
     */
    public function setSlug(string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    /*
     * Get the product creation date.
     * 
     * @return \DateTimeImmutable|null
     */
    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    /*
     * Set the product creation date.
     * 
     * @param \DateTimeImmutable $created_at
     * @return static
     */
    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    /*
     * Get the product last update date.
     * 
     * @return \DateTimeImmutable|null
     */
    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    /*
     * Set the product last update date.
     * 
     * @param \DateTimeImmutable $updated_at
     * @return static
     */
    public function setUpdatedAt(\DateTimeImmutable $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }

}
