<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert; 
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[ORM\UniqueConstraint(name: 'UNIQENTIFIER_EMAIL', fields: ['email'])]
#[ORM\HasLifecycleCallbacks] 
class User implements UserInterface, PasswordAuthenticatedUserInterface
{

    ################################
    ################################
    ########## ATTRIBUTES ##########
    ################################
    ################################

    /* The user ID, auto-generated by the database.
     * 
     * @var int|null
     */
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(['default'])]
    private ?int $id = null;

    /* The user's email address, must be unique.
     * 
     * @var string|null
     */
    #[ORM\Column(length: 180)]
    #[Assert\NotBlank]
    #[Assert\Email] // Ensures the email is valid
    #[Groups(['default'])]
    private ?string $email = null;

    /* The user's roles, stored as an array of strings.
     * 
     * @var list<string>
     */
    #[ORM\Column]
    #[Assert\NotBlank] 
    private array $roles = [];

    /* The user's hashed password.
     * 
     * @var string|null
     */
    #[ORM\Column]
    #[Assert\NotBlank] 
    private ?string $password = null;

    /* The user's first name, optional.
     * 
     * @var string|null
     */
    #[ORM\Column(length: 100, nullable: true)]
    #[Assert\Length(max: 100)] 
    private ?string $firstName = null;

    /* The user's last name, optional.
     * 
     * @var string|null
     */
    #[ORM\Column(length: 100, nullable: true)]
    #[Assert\Length(max: 100)] 
    private ?string $lastName = null;

    /* The user's account creation date.
     * 
     * @var \DateTimeImmutable|null
     */
    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt;

    /* The user's last update date.
     * 
     * @var \DateTimeImmutable|null
     */
    #[ORM\Column]
    private ?\DateTimeImmutable $updatedAt;

    /* The user's last login date, optional.
     * 
     * @var \DateTimeImmutable|null
     */
    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $lastLogin = null;

    ################################
    ################################
    ########## RELATIONS ###########
    ################################
    ################################

    /* The collection of addresses associated with the user.
     * 
     * @var Collection<int, Address>
     */
    #[ORM\OneToMany(targetEntity: Address::class, mappedBy: 'user')]
    private Collection $addresses;

    /* The collection of orders associated with the user.
     * 
     * @var Collection<int, Order>
     */
    #[ORM\OneToMany(targetEntity: Order::class, mappedBy: 'user')]
    private Collection $orders;

    ################################
    ################################
    ########## LIFECYCLE ###########
    ################################
    ################################

    /*
     * Automatically sets the createdAt and updatedAt fields to the current date and time when the user is created.
     * 
     * @ORM\PrePersist
     */
    #[ORM\PrePersist]
    public function setCreatedAtValue(): void
    {
        $this->createdAt = new \DateTimeImmutable();
        $this->updatedAt = new \DateTimeImmutable();
    }

    /*
     * Automatically sets the updatedAt field to the current date and time when the user is updated.
     * 
     * @ORM\PreUpdate
     */
    #[ORM\PreUpdate]
    public function setUpdatedAtValue(): void
    {
        $this->updatedAt = new \DateTimeImmutable();
    }

    ###############################
    ######### CONSTRUCTOR #########
    ###############################

    /**
     * User constructor.
     * Initializes the addresses and orders collections.
     */
    public function __construct()
    {
        $this->addresses = new ArrayCollection();
        $this->orders = new ArrayCollection();
    }

    ################################
    ################################
    ###### GETTERS & SETTERS #######
    ################################
    ################################

    /**
     * Getters and Setters for the User entity.
     * 
     * These methods allow you to get and set the values of the user's attributes.
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /*
     * Get the user's email address.
     * 
     * @return string|null
     */
    public function getEmail(): ?string
    {
        return $this->email;
    }

    /*
     * Set the user's email address.
     * 
     * @param string $email
     * @return static
     */
    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /*
     * Get the user's roles.
     * 
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        $roles[] = 'ROLE_USER'; 

        return array_unique($roles);
    }

    /*
     * Set the user's roles.
     * 
     * @param list<string> $roles
     * @return static
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /*
     * Get the user's hashed password.
     * 
     * @return string|null
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    /*
     * Set the user's hashed password.
     * 
     * @param string $password
     * @return static
     */
    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /*
     * Get the user's first name.
     * 
     * @return string|null
     */
    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    /*
     * Set the user's first name.
     * 
     * @param string|null $firstName
     * @return static
     */
    public function setFirstName(?string $firstName): static
    {
        $this->firstName = $firstName;

        return $this;
    }

    /*
     * Get the user's last name.
     * 
     * @return string|null
     */
    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    /*
     * Set the user's last name.
     * 
     * @param string|null $lastName
     * @return static
     */
    public function setLastName(?string $lastName): static
    {
        $this->lastName = $lastName;

        return $this;
    }

    /*
     * Get the user's account creation date.
     * 
     * @return \DateTimeImmutable|null
     */
    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    /*
     * Set the user's account creation date.
     * 
     * @param \DateTimeImmutable $createdAt
     * @return static
     */
    public function setCreatedAt(\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /*
     * Get the user's last update date.
     * 
     * @return \DateTimeImmutable|null
     */
    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    /*
     * Set the user's last update date.
     * 
     * @param \DateTimeImmutable $updatedAt
     * @return static
     */
    public function setUpdatedAt(\DateTimeImmutable $updatedAt): static
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /*
     * Get the user's last login date.
     * 
     * @return \DateTimeImmutable|null
     */
    public function getLastLogin(): ?\DateTimeImmutable
    {
        return $this->lastLogin;
    }

    /*
     * Set the user's last login date.
     * 
     * @param \DateTimeImmutable|null $lastLogin
     * @return static
     */
    public function setLastLogin(?\DateTimeImmutable $lastLogin): static
    {
        $this->lastLogin = $lastLogin;

        return $this;
    }

    /*
     * Get the collection of addresses associated with the user.
     * 
     * @return Collection<int, Address>
     */
    public function getAddresses(): Collection
    {
        return $this->addresses;
    }

    /*
     * Add an address to the user's collection of addresses.
     * 
     * @param Address $address
     * @return static
     */
    public function addAddress(Address $address): static
    {
        if (!$this->addresses->contains($address)) {
            $this->addresses->add($address);
            $address->setUser($this);
        }

        return $this;
    }

    /*
     * Remove an address from the user's collection of addresses.
     * 
     * @param Address $address
     * @return static
     */
    public function removeAddress(Address $address): static
    {
        if ($this->addresses->removeElement($address)) {
            if ($address->getUser() === $this) {
                $address->setUser(null);
            }
        }

        return $this;
    }

    /*
     * Get the collection of orders associated with the user.
     * 
     * @return Collection<int, Order>
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    /*
     * Add an order to the user's collection of orders.
     * 
     * @param Order $order
     * @return static
     */
    public function addOrder(Order $order): static
    {
        if (!$this->orders->contains($order)) {
            $this->orders->add($order);
            $order->setUserId($this);
        }

        return $this;
    }

    /*
     * Remove an order from the user's collection of orders.
     * 
     * @param Order $order
     * @return static
     */
    public function removeOrder(Order $order): static
    {
        if ($this->orders->removeElement($order)) {
            if ($order->getUserId() === $this) {
                $order->setUserId(null);
            }
        }

        return $this;
    }

    /**
     * A visual identifier that represents this user, return the email as the unique identifier
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email; 
    }

    /**
     * Removes sensitive data from the user.
     *
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // For example: $this->plainPassword = null;
    }
}
